---
title: "Alexey Katin"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
---
  output:
  html_document: default
  word_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div class="row">
  <div class="col-12 col-md-8">
   +1 919 633 0911 <br>
  akatin@ncsu.edu <br>
  [www.alexeykatin.xyz](http://alexeykatin.xyz)</div>
  <div class="col-6 col-md-4">
 
  </div>
</div>

***

#### Professional interests:

* Statistical and differential equation modeling, machine learning, Bayesian inference
* Data analysis and visualization (maps, tables, and figures)
* Water quality, hydrologic and ecological modeling

***

#### Education

* **Ph.D**. Department of Civil, Construction & Environmental Engineering (CCEE) (2016–2021)<br>
**North Carolina State University** (NCSU) (Raleigh, NC, USA)<br>
Advisor: Daniel R. Obenour<br>
Dissertation: [Bayesian Modeling of Coastal Eutrophication to Inform Management Solutions for Hypoxia and Algal Blooms](https://repository.lib.ncsu.edu/bitstream/handle/1840.20/38491/etd.pdf?sequence=1&isAllowed=y) 

* **M.S.** Hydro Science and Engineering (2013–2015)<br>
**Technische Universität Dresden** (Dresden, Germany)<br>
Advisors: Mitsuyo Saito, Kenji Okubo, Rudolf Liedl<br>
Thesis: Quantitative evaluation of submarine groundwater discharge in granitic coastal area with the use of ^222^Rn as a natural tracer including diffusive flux from the benthic sediment 

* **B.S.** Economics (2006–2010)<br>
**National University of Science and Technology (MISIS)** (Moscow, Russia)<br>
Advisor: Theodor B. Rubinshtein<br>
Thesis: Credit risk management for “Alfa-Bank”

* **B.S.** Environmental Engineering (2004–2009)<br>
**National University of Science and Technology (MISIS)** (Moscow, Russia)<br>
Advisor: Yuri M. Kochnov<br>
Thesis: Development of recommendations for improving gas purification system for arc shaft furnace “Severstal” in order to reduce energy costs

***

#### Positions held

**Postdoctoral Scholar**. NCSU, CCEE (2021–present)

* Developed Bayesian models linking spatio-temporal distributions of marine species (Brown and White Shrimp) to environmental, water quality and anthropogenic factors (manuscript in prep.) 
* Teaching Hydraulics class (CE 282), Summer 2, 2022

**Research Assistant**. NCSU, CCEE (2016–2020)

* Developed novel [Bayesian mechanistic biogeochemical model](#nre_hypoxia) to predict dissolved oxygen concentration for the Neuse Estuary, NC  

* Leveraged model for short-term [hypoxia forecasting](#blog_posts) to inform fisheries and watershed managers in advance about the expected conditions

* Developed Bayesian empirical and process-based predictive models to understand [how environmental factors control phytoplankton](#nre_chla) in the river-dominated estuary. Tested the system sensitivity to nutrient loading variations in order to comply with state water quality standard

* Used R to process and analyze data, produce figures, and code all models

* Provided annual forecast for the Gulf of Mexico (GoM) hypoxia. Suggested [updates to the existing model](#gom_ensemble) to include the long-term effect of nutrient loadings in the predictions of the GoM hypoxic zone

**Graduate Teaching Assistant**. CE 383 – Hydrology and Urban Water Systems. NCSU, CCEE (2018–2020)

* Graded biweekly student assignments

* Assisted students with questions during regular office hours

**Intern**. Helmholtz-Zentrum Dresden-Rossendorf, Dresden, Germany (2014)

* Converted technical documentation into html version with equations embedded using LaTeX 

**Marketing Executive**. Bosch Rexroth, Moscow, Russia (2010–2013)

* Planned and organized company representation at exhibitions and conferences (full event management)

* Analyzed local industrial hydraulics market and competitors

* Administrated and managed corporate website

* Designed sales brochures according to corporate style. Worked with printing agencies

***

#### Scholarly works 

1. <a id="gom_ensemble"></a>Scavia, D., Bertani, I., Obenour, D.R., Turner, R.E., Forrest, D.R., Katin, A. (2017). Ensemble modeling informs hypoxia management in the northern Gulf of Mexico. Proceedings of the National Academy of Sciences, Vol. 114, 8823-8828. [10.1073/pnas.1705293114](http://www.pnas.org/content/114/33/8823.abstract)

2. <a id="nre_hypoxia"></a>Katin, A., Del Giudice, D., Obenour, D.R. (2019). Modeling biophysical controls on hypoxia in a shallow estuary using a Bayesian mechanistic framework. Environmental modeling and software, 120. [10.1016/j.envsoft.2019.07.016](https://www.sciencedirect.com/science/article/pii/S1364815218311320) 

3. <a id="nre_chla"></a>Katin, A., Del Giudice, D., Hall, N.S., Paerl, H.W., Obenour, D.R. (2021). Simulating algal dynamics within a Bayesian framework to evaluate controls on estuary productivity. Ecological modelling, Vol. 447. [10.1016/j.ecolmodel.2021.109497](https://www.sciencedirect.com/science/article/pii/S0304380021000685)

4. Katin, A., Del Giudice, D., Obenour, D.R. (2022). Temporally resolved coastal hypoxia forecasting and uncertainty assessment via Bayesian mechanistic modeling, Hydrology and Earth System Sciences, Volume 26. [10.5194/hess-26-1131-2022](https://doi.org/10.5194/hess-26-1131-2022)

***

#### Other related experience  

* Assisted in collecting water quality samples and CTD profiling at University Lake, NC (2017)

* Collected water quality samples (nutrients, chlorophyll a) at the Neuse River, NC as a part of monitoring project (2016)

* Sampled sediment and deployed sensors (temperature, salinity) at the Ikuchijima island, Hiroshima area, Japan (2015)

* Accomplished study project during Masters: Testing the performance of spatial interpolation techniques for mapping precipitation fields in Saxony, Germany (2014). Interpolation and output figures were performed in R 

***

#### Presentations
Katin, A., Obenour, D.R., Del Giudice D. "Summerlong, climate-driven hypoxia forecasts for the northern Gulf of Mexico via Bayesian mechanistic modeling", 26th Biennial Conference of Coastal and Estuarine Research Federation (CERF), November, 2021.

Katin, A., Obenour, D.R., Del Giudice D. [“Contrasting nutrient management implications from statistical and process-based estuary phytoplankton models”](https://cerf.confex.com/cerf/2019/meetingapp.cgi/Paper/6594), 25th Biennial Conference of the Coastal and Estuarine Research Federation (CERF). Mobile, AL. November 2019.

Katin, A., Obenour, D.R., Del Giudice, D. “Development and application of a probabilistic hypoxia forecasting model for the Neuse Estuary”, Water Resources Research Institute (WRRI) Annual Conference. Raleigh, NC. March, 2019.

Katin, A., Del Giudice D., Paerl, H.W., Obenour, D.R. [“Modeling biophysical controls on hypoxia for the Neuse River Estuary using a Bayesian framework”](https://ecm.github.io/ECM15/abstracts.html#Modeling%20biophysical%20controls%20on%20hypoxia%20for%20the%20Neuse%20River%20Estuary%20using%20a%20Bayesian%20framework), Estuarine and Coastal Modeling Conference (ECM15). Seattle, WA. June 2018.

Katin, A., Obenour, D.R. “Hypoxia and algal bloom modeling for the Neuse River Estuary”, North Carolina Sea Grant Conference. Raleigh, NC. April 2017. 

***

#### Other Publications targeting non-scientific audience <a id="blog_posts"></a>

1. [Forecasting Hypoxia, Algal Blooms for the Neuse River Estuary](https://ncseagrant.ncsu.edu/currents/2016/10/forecasting-hypoxia-algal-blooms-for-the-neuse-river-estuary/), 2016

2. [Model Forecasts Severe Hypoxia through August in Neuse Estuary](https://ncseagrant.ncsu.edu/news/2018/07/model-forecasts-severe-hypoxia-through-august-in-neuse-estuary/), 2018

3. [Tropical Systems Disrupt Neuse River Oxygen Levels](https://ncseagrant.ncsu.edu/currents/2019/01/tropical-systems-disrupt-neuse-river-oxygen-levels/), 2018

4. [Researchers Forecast Healthier Neuse River Oxygen Levels](https://ncseagrant.ncsu.edu/news/2019/06/researchers-forecast-healthier-neuse-river-oxygen-levels/), 2019

5. [Midsummer Neuse River Forecast Shows Greater Potential for Fish Kills](https://ncseagrant.ncsu.edu/currents/2020/06/midsummer-neuse-river-forecast-shows-greater-potential-for-fish-kills/), 2020

6. [Summer 2021 Hypoxia Forecast: Fish Kills Less Likely Than Usual in the Neuse River Estuary](https://ncseagrant.ncsu.edu/currents/2021/06/summer-2021-hypoxia-forecast-fish-kills-less-likely-than-usual-in-the-neuse-river-estuary/), 2021

7. [Neuse Oxygen Levels Could Bring Summer Fish Kills](https://ncseagrant.ncsu.edu/currents/2022/06/neuse-oxygen-levels-could-bring-summer-fish-kills/), 2022

8. [2022 Experimental Forecast of Brown and White Shrimp Summer Distributions on the Louisiana Shelf](https://drive.google.com/file/d/1ygUUzVsp_maWAVEdEj9UP7bUNYhhd9Tn/view), 2022

***

#### Software Experience

Modeling: R, Python, MATLAB, SAS, Stan, ArcGIS, GRASS, QUAL2K, WEAP, IRIC, Lindo, Minteq

Web: HTML, Gauss, First spirit, Joomla, Bitrix, WordPress

Graphics: Adobe (Photoshop, Illustrator, InDesign), Corel, GIMP

***

#### Honors

* Full travel DAAD stipend covering two semesters in Japan (2014-2015)  

* Full tuition fellowship at North Carolina State University (2016-2020)

* Mentored Teaching Fellowship (MTF) Award (Fall 2020)